language: java

jdk:
  - oraclejdk8

script: mvn test

after_success:
  - mvn clean test jacoco:report coveralls:report
  - bash <(curl -s https://codecov.io/bash)

sudo: false

branches:
  only:
  - master

notifications:
  email:
  - brogeriom@axpe.com